version: "3"

services:
  jupyter:
    container_name: jn
    build:
      context: ${PDIR}/
      dockerfile: ${PDIR}/Dockerfile
    restart: always
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
        - ${PDIR/jupyter:${main_dir}
    env_file:
      - ${PDIR}/jupyter/conf/secrets.env.sample
    entrypoint: /usr/bin/env bash
    command: setup.sh