version: "3"

services:
  jupyter:
    container_name: jn
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
        - ./jupyter:${main_dir}
    env_file:
      - ./jupyter/conf/secrets.env.sample
    entrypoint: /usr/bin/env bash
    command: setup.sh